.job_template: &job_definition
  only:
    - master
    - /^develop.*$/
    - /^.*review(_[0-9]+)?$/
    - tags
    - schedules
  tags:
    - docker
    - neutrino

image: jruby:9.2.6

before_script:
  - gem install bundler
  - bundler install

rspec:
  <<: *job_definition
  stage: test
  script:
    - rspec

#For when rubocop works again
# rubocop:
#   <<: *job_definition
#   stage: test
#   script:
#     - rubocop
