# Run rubocop on your git diff with the following command:
# $ git diff --name-only develop_X.X.0 | xargs rubocop

AllCops:
  TargetRubyVersion: 2.3.7

# Test specific exceptions
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'features/step_definitions/*'

    # Rules that are not enforced across the codebase nor during code review
Metrics:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

# We use 'fail' instead of 'raise' across the codebase - this suppresses the warning
Style/SignalException:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false


Lint/UriEscapeUnescape:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
